'use client';
import {Component,useCallback,useEffect,useRef,useState} from 'react';
import {Activity,CircleDot,FlaskConical,Settings2,ShieldCheck,PlugZap,Database,Download,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import Wheel from '@/components/wheel/Wheel';
import Chart from '@/components/chart/Chart';
import Settings from '@/components/dashboard/Settings';
import DataPanel from '@/components/dashboard/DataPanel';
import Lab from '@/components/dashboard/Lab';
import {Choice,fmt,date,download} from '@/components/dashboard/Controls';
import {api,API,type Snapshot,type Config} from '@/lib/api';
import {liveConnection} from '@/lib/live';
import {SymbolSelector,ExecutionHistory,ResearchControls} from '@/components/dashboard/MultiSymbolPanels';
const TF=['M1','M5','M15','M30','H1','H4','D1'];
function Panel({title,tag,children}:{title:string,tag?:string,children:React.ReactNode}){return <article className="panel"><div className="panel-title"><h2>{title}</h2><span>{tag}</span></div>{children}</article>}
function Home(){
 const[snapshot,setSnapshot]=useState<Snapshot|null>(null),[config,setConfig]=useState<Config|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview'),[tf,setTf]=useState('M1'),[signals,setSignals]=useState<any[]>([]),[datasets,setDatasets]=useState<any[]>([]),[audit,setAudit]=useState<any>(null),[visual,setVisual]=useState<Config>({}),[link,setLink]=useState('CONNECTING'),[version,setVersion]=useState(''),[execution,setExecution]=useState<any>(null),[symbols,setSymbols]=useState<any[]>([]),[activeSymbol,setActiveSymbol]=useState('');
 const snapshotRef=useRef<Snapshot|null>(null);
 const acceptSnapshot=useCallback((next:Snapshot)=>{
  const incomingTick=next?.tick;
  const currentTick=snapshotRef.current?.tick;
  const incomingTime=Number(incomingTick?.time_msc ?? incomingTick?.normalized_utc_timestamp ?? incomingTick?.time ?? 0);
  const currentTime=Number(currentTick?.time_msc ?? currentTick?.normalized_utc_timestamp ?? currentTick?.time ?? 0);
  // REST bootstrap or a delayed socket frame must not replace a newer valid
  // quote with an empty/older snapshot.
  if(currentTick && (!incomingTick || (incomingTime>0 && currentTime>incomingTime)))return;
  snapshotRef.current=next;setSnapshot(next);
  setError(next?.tick?.bid!=null&&next?.tick?.ask!=null ? '' : (next?.error||''));
 },[]);
 const refresh=useCallback(()=>{Promise.all([api('/api/signals'),api('/api/datasets')]).then(([s,d])=>{setSignals(Array.isArray(s)?s:[]);setDatasets(Array.isArray(d)?d:[])}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{api('/api/config').then(x=>{setConfig(x.config);setActiveSymbol(x.config.symbol);setVersion(x.version)}).catch(e=>setError(e.message));api('/api/execution/status').then(setExecution).catch(e=>setError(e.message));api('/api/mt5/symbols').then(x=>setSymbols(x.symbols||[])).catch(()=>{});refresh();try{setVisual(JSON.parse(localStorage.getItem('timewheel.visual')||'{}'))}catch{}const timer=setInterval(()=>{refresh();api('/api/execution/status').then(setExecution).catch(()=>{})},12000);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{
  let active=true;
  api(`/api/snapshot?timeframe=${encodeURIComponent(tf)}`).then(x=>{if(active)acceptSnapshot(x)}).catch(()=>{});
  const cleanup=liveConnection.connect(tf,{status:setLink,data:acceptSnapshot});
  return()=>{active=false;cleanup()};
 },[tf,acceptSnapshot]);
 // A backend that was offline at page load must also restore REST settings after WS recovery.
 useEffect(()=>{if(snapshot?.strategy_version&&snapshot.strategy_version!==version){let active=true;api('/api/config').then(x=>{if(active){setConfig(x.config);setVersion(x.version)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}}},[snapshot?.strategy_version,version]);
 const connect=async(symbol:any=activeSymbol)=>{if(typeof symbol!=='string'||!symbol)return;setBusy(true);setSnapshot(null);setError('');try{const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('Symbol switch timed out; market data is unavailable')),10000));await Promise.race([api('/api/feed/connect',{method:'POST',body:JSON.stringify({symbol})}),timeout]);const x=await Promise.race([api('/api/config'),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Symbol metadata request timed out')),5000))]) as any;setConfig(x.config);setActiveSymbol(x.config.symbol);setVersion(x.version)}catch(e){setError((e as Error).message);setSnapshot(null)}finally{setBusy(false)}};
 const setDisplay=(v:Config)=>{setVisual(v);localStorage.setItem('timewheel.visual',JSON.stringify(v))};
 const executionAction=async(enable:boolean)=>{setBusy(true);try{setExecution(await api('/api/execution/'+(enable?'enable':'stop'),{method:'POST'}));setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{const selects=Array.from(document.querySelectorAll('select'));const el=selects.find(x=>x.parentElement?.textContent?.includes('Execution timeframe')) as HTMLSelectElement|undefined;if(!el)return;el.style.display='none';const host=el.parentElement as HTMLElement;let box=host.querySelector('[data-timeframe-checkboxes]') as HTMLElement|null;if(!box){box=document.createElement('div');box.dataset.timeframeCheckboxes='true';host.appendChild(box)}box.innerHTML='';const selected=execution?.selected_timeframes||['M15'];const summary=document.createElement('div');summary.textContent='Selected execution timeframes: '+selected.join(', ');box.appendChild(summary);['M1','M5','M15','M30','H1','H4','D1'].forEach(tf=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.value=tf;input.checked=selected.includes(tf);input.onchange=()=>{const values=Array.from(box!.querySelectorAll('input:checked')).map(x=>(x as HTMLInputElement).value);setExecution((old:any)=>({...old,selected_timeframes:values,timeframe:values[0]||'M15'}))};label.append(input,` ${tf}`);box!.appendChild(label)});return()=>{el.style.display='';box?.remove()}},[execution?.selected_timeframes]);
 useEffect(()=>{const selects=Array.from(document.querySelectorAll('select'));const daily=selects.find(x=>x.parentElement?.textContent?.includes('Maximum trades / day'));if(daily)[50,100,150,200].forEach(n=>{if(!Array.from(daily.options).some(o=>o.value===String(n)))daily.add(new Option(String(n),String(n)))});const positions=selects.find(x=>x.parentElement?.textContent?.includes('Maximum open positions'));if(positions)[20,50].forEach(n=>{if(!Array.from(positions.options).some(o=>o.value===String(n)))positions.add(new Option(String(n),String(n)))})},[execution]);
 const saveExecutionSettings=async()=>{if(!execution)return;setBusy(true);try{setExecution(await api('/api/execution/settings',{method:'PUT',body:JSON.stringify({selected_timeframes:execution.selected_timeframes,fixed_lot:Number(execution.fixed_lot),max_trades_per_day:execution.max_trades_per_day===null?null:Number(execution.max_trades_per_day),max_positions:execution.max_positions===null?null:Number(execution.max_positions),max_positions_per_timeframe:execution.max_positions_per_timeframe===null?null:Number(execution.max_positions_per_timeframe),allow_opposite_direction:Boolean(execution.allow_opposite_direction),cooldown_minutes:execution.cooldown_minutes===null?null:Number(execution.cooldown_minutes),maximum_spread:execution.maximum_spread===null?null:Number(execution.maximum_spread),duplicate_signal_protection:Boolean(execution.duplicate_signal_protection),one_trade_per_unique_signal:Boolean(execution.one_trade_per_unique_signal),stop_loss_mode:'strategy_invalidation',take_profit_mode:'strategy_target_1'})}));setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const a=snapshot?.analysis,w=snapshot?.wheel;const scoped=signals.filter(s=>{const payload=s?.payload||{};return payload.source===snapshot?.provider&&payload.dataset_id===snapshot?.dataset_id&&payload.symbol===snapshot?.symbol});
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const controller=new AbortController();Promise.resolve(mc.registerTool({name:'read_time_wheel_state',description:'Read current displayed market-data status, selected timeframe and numerical analysis. Does not place orders or change settings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({provider:snapshot?.provider,timeframe:tf,wheel:w,direction:a?.direction,error})},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[snapshot,tf,w,a,error]);
 return <main className="terminal"><header className="topbar"><div className="brand"><CircleDot size={29}/><div>DIGITAL TIME WHEEL <span>MT5</span><small>INDEPENDENT MARKET RESEARCH</small></div></div><div className="header-right"><span className="status-dot"/>Feed: {snapshot?.provider||'disconnected'}<span className="pill">{link==='CONNECTED'?'BACKEND ONLINE':link}</span><Button disabled={busy} onClick={connect}><PlugZap size={15}/>{busy?'Connecting…':'Connect MT5'}</Button></div></header>
 <section className="section-body" aria-label="Market symbol selection"><SymbolSelector symbol={activeSymbol||""} symbols={symbols} onChange={(value)=>{setActiveSymbol(value);if(symbols.some(item=>item.symbol===value))void connect(value)}}/></section>
 <section className="notice"><b>{execution?.state||'TRADING DISABLED'}</b> · {(execution?.selected_timeframes||['M15']).join(' + ')} · {execution?.fixed_lot??0.01} lot · {execution?.daily_sent_trades??0}/{execution?.max_trades_per_day??'∞'} today · {execution?.account?.demo_confirmed?'DEMO CONFIRMED':'DEMO NOT CONFIRMED'} <Button disabled={busy||execution?.enabled} onClick={()=>executionAction(true)}>DEMO AUTO TRADING</Button><Button variant="destructive" disabled={busy||!execution?.enabled} onClick={()=>executionAction(false)}>STOP AUTO TRADING</Button></section>
 {execution&&<section className="panel section-body"><div className="panel-title"><h2>DEMO AUTO TRADING SETTINGS</h2><span>DEMO ONLY</span></div><div className="settings-grid"><label>Execution timeframe<select value={execution.timeframe} onChange={e=>setExecution({...execution,timeframe:e.target.value})}>{TF.map(x=><option key={x}>{x}</option>)}</select></label><label>Fixed lot size<input type="number" min="0.01" step="0.01" value={execution.fixed_lot} onChange={e=>setExecution({...execution,fixed_lot:e.target.value})}/></label><label>Maximum trades / day<select value={execution.max_trades_per_day??'disabled'} onChange={e=>setExecution({...execution,max_trades_per_day:e.target.value==='disabled'?null:e.target.value})}><option value="disabled">Disabled</option>{[1,2,3,5,10].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Maximum open positions<select value={execution.max_positions} onChange={e=>setExecution({...execution,max_positions:e.target.value})}>{[1,2,3,5,10].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Cooldown<select value={execution.cooldown_minutes??'disabled'} onChange={e=>setExecution({...execution,cooldown_minutes:e.target.value==='disabled'?null:e.target.value})}><option value="disabled">Disabled</option>{[1,5,15,30,60].map(x=><option key={x} value={x}>{x} minutes</option>)}</select></label><label>Maximum spread<input placeholder="Disabled" type="number" min="0" step="0.01" value={execution.maximum_spread??''} onChange={e=>setExecution({...execution,maximum_spread:e.target.value===''?null:e.target.value})}/></label><label><input type="checkbox" checked={execution.duplicate_signal_protection} onChange={e=>setExecution({...execution,duplicate_signal_protection:e.target.checked})}/> Duplicate signal protection</label><label><input type="checkbox" checked={execution.one_trade_per_unique_signal} onChange={e=>setExecution({...execution,one_trade_per_unique_signal:e.target.checked})}/> One trade per unique signal</label><label>Stop Loss mode<strong>Existing strategy invalidation</strong></label><label>Take Profit mode<strong>Existing strategy target 1</strong></label></div><div className="toolbar"><Button disabled={busy} onClick={saveExecutionSettings}>Save DEMO settings</Button><span className="pill">{execution.enabled?'ENABLED':'DISABLED'} · {execution.timeframe} · {execution.fixed_lot} lot</span></div><div className="notice"><b>LIVE EXECUTION STATUS</b> · DEMO AUTO TRADING: {execution.enabled?'ENABLED':'DISABLED'} · {execution.open_positions?.length||0}/{execution.max_positions} positions · {execution.daily_sent_trades}/{execution.max_trades_per_day??'∞'} today · Current signal: {snapshot?.timeframes?.find((r:any)=>r.timeframe===execution.timeframe)?.label||'Awaiting data'} · Last executed: {execution.last_executed_signal?.request?.signal_id||'None'} · {execution.blocking_reason||'No block'}</div></section>}
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList variant="line" className="navigation"><TabsTrigger value="overview"><Activity size={15}/>Overview</TabsTrigger><TabsTrigger value="lab"><FlaskConical size={15}/>Research Lab</TabsTrigger><TabsTrigger value="audit"><ShieldCheck size={15}/>Signal audit</TabsTrigger><TabsTrigger value="settings"><Settings2 size={15}/>Model settings</TabsTrigger><TabsTrigger value="data"><Database size={15}/>Market data</TabsTrigger><TabsTrigger value="execution-history">Execution History</TabsTrigger><small>CONTROLLED DEMO EXECUTION ONLY</small></TabsList>
 {error&&<div role="alert" className="notice error">{error}</div>}{link==='RECONNECTING'&&<div role="status" className="notice">Connection to the backend was interrupted. Displayed observations may be old; reconnecting automatically.</div>}
 <TabsContent value="overview"><section className="market-heading"><div><small>{symbols.find(s=>s.symbol===(snapshot?.symbol||activeSymbol))?.description||snapshot?.symbol||activeSymbol||'No symbol selected'}</small><h1>{snapshot?.symbol||config?.symbol||''} <span>Market observatory</span></h1></div><div className="quote">{fmt(snapshot?.tick?.bid??a?.price)}<small>{snapshot?.tick?'BID · ASK '+fmt(snapshot.tick.ask)+' · SPREAD '+fmt(snapshot.tick.spread):a?'HISTORICAL CLOSE':'WAITING FOR MARKET DATA'}</small></div><div><small>{error||snapshot?.stale?'HISTORICAL / STALE OBSERVATION':'ANALYSIS STATE'}</small><strong className={a?.direction==='BUY'?'positive':a?.direction==='SELL'?'negative':''}>{a?.label||'NO DATA'}</strong></div><div className="tf-choice"><Choice label="Chart timeframe" value={tf} options={TF} onChange={setTf}/></div></section>
 {snapshot?.analysis_asof&&<div className="asof">Analysis as of {date(snapshot.analysis_asof)} · {snapshot.provider==='MT5'?'Closed bars generate signals; ticks animate the wheel.':'Historical dataset — no live bid/ask.'}</div>}
 <section className="workspace"><Panel title="Price structure" tag={tf}>{snapshot?.candles?.length?<Chart bars={snapshot.candles} analysis={a} signals={scoped} options={visual} timeframe={tf}/>:<div className="chart-empty"><Activity size={38}/><h3>{snapshot?.provider==='MT5'?'Candle history unavailable':'Connect market data'}</h3><p>{snapshot?.provider==='MT5'?(snapshot.timeframes?.find((r:any)=>r.timeframe===tf)?.reason||'Waiting for candle history. Live quotes update the wheel independently.'):'Connect MT5 or import historical OHLC data to see candles and testable analysis.'}</p><Button variant="outline" onClick={()=>setTab('data')}>Set up market data</Button></div>}</Panel><Panel title="Time Wheel · عجلة الزمن" tag="36 × 10°"><Wheel state={w} config={config} clockAngle={snapshot?.clock_angle||0} options={{...visual,fibLevels:a?.fibonacci}}/><div className="wheel-key"><span className="market-accent">● Time</span><span className="teal">● Price</span><span>360° geometry</span></div>{w&&<div className="wheel-stats"><div><small>PRICE ANGLE</small><b>{fmt(w.price_angle)}°</b></div><div><small>SEPARATION</small><b>{fmt(w.angular_distance)}°</b></div><div><small>CONFLUENCE</small><b>{w.confluence}</b></div></div>}</Panel><Panel title="Timeframe alignment" tag="7 TF"><div className="tf-table">{TF.map(t=>{const row=snapshot?.timeframes?.find((r:any)=>r.timeframe===t);return <div key={t} title={row?.reason||`Wheel ${row?.numerical_signal}; structure ${row?.structure}; momentum ${row?.momentum}`} onClick={()=>setTf(t)}><b>{t}</b><span className={row?.direction==='BUY'?'positive':row?.direction==='SELL'?'negative':''}>{row?.available?row.label:'Awaiting data'}{row?.available&&<small>{row.structure} · M {row.momentum}</small>}</span><em>{row?.available?fmt(row.confidence,0):'—'}</em></div>})}</div><div className="panel-note">Scores express weighted evidence, not a calibrated probability. Hover a row to inspect wheel, structure and momentum.</div></Panel></section>
 <section className="lower-grid"><Panel title="Signal reasoning" tag="NUMERICAL → TECHNICAL → COMBINED">{a?<><div className="score-strip">{Object.entries(a.scores).map(([k,v])=><div key={k}><small>{k.toUpperCase()} SCORE</small><b>{fmt(v,1)}</b></div>)}</div><div className="explanation"><p>Numerical: {a.numerical_signal} · Technical: {a.technical_signal} · Combined: {a.direction}</p><ul>{a.reasons.map((r:string,i:number)=><li key={i}>{r}</li>)}</ul><details><summary>Component contributions and indicator values</summary><pre>{JSON.stringify({components:a.components,indicators:a.indicators},null,2)}</pre></details></div></>:<p className="panel-note">No signal has been calculated without market data. Numerical relationships remain experimental until independently validated.</p>}</Panel><Panel title="Targets and Digital Gates" tag="EXACT RATIONALES">{a?<div className="section-body">{a.targets?.length?a.targets.map((t:any,i:number)=><details className="target" key={i}><summary>Target {i+1}<b>{fmt(t.price)}</b><span>{t.reasons.map((r:any)=>r.source).filter((v:string,i:number,arr:string[])=>arr.indexOf(v)===i).join(' + ')}</span></summary><pre>{JSON.stringify(t.reasons,null,2)}</pre></details>):<p className="panel-note">No directional target while the combined state is neutral.</p>}{a.invalidation&&<p className="panel-note">Invalidation {fmt(a.invalidation.price)} · {a.invalidation.reason}</p>}<h3 className="subheading">Triggered gates</h3><div className="toolbar">{w?.gates?.length?w.gates.map((g:string)=><span className="pill" key={g}>{g.replaceAll('_',' ')}</span>):'No enabled gate triggered'}</div><small>ROOTS · PRICE {w?.price_root} / TIME {w?.time_root} / ANGLE {w?.angle_root} / DATE {w?.date_root}</small><details className="detail"><summary>Compare all time-root models</summary><pre>{JSON.stringify(w?.models,null,2)}</pre></details></div>:<p className="panel-note">Targets are derived from wheel levels, angular projections, past structure, Fibonacci and ATR. No target is forced.</p>}</Panel></section>
 <div className="toolbar"><Button variant="outline" onClick={()=>setTab('lab')}><FlaskConical size={14}/>Test this model</Button><Button variant="outline" onClick={()=>setTab('audit')}><ShieldCheck size={14}/>Inspect immutable signals</Button><a href={API+'/api/docs/VIDEO_REVERSE_ENGINEERING_REPORT.md'} target="_blank" rel="noreferrer"><BookOpen size={13} style={{display:'inline',marginRight:6}}/>Video evidence report</a><a href={API+'/api/docs/TIME_WHEEL_RESEARCH.md'} target="_blank" rel="noreferrer">Mathematical research notes</a></div></TabsContent>
 <TabsContent value="settings">{config?<Settings config={config} onSaved={c=>{setConfig(c);setVersion(String(Date.now()));refresh()}} visual={visual} onVisual={setDisplay}/>:<div className="empty">Waiting for backend settings…</div>}</TabsContent><TabsContent value="data"><DataPanel activeSymbol={activeSymbol} snapshot={snapshot} datasets={datasets} refresh={refresh} onSelected={()=>{api('/api/config').then(x=>{setConfig(x.config);setVersion(x.version)});setVersion(String(Date.now()))}}/></TabsContent><TabsContent value="lab">{config&&<><ResearchControls datasets={datasets} config={config} onRun={()=>setError("Research requires an explicit symbol, timeframe, and matching dataset")}/><Lab config={config} datasets={datasets}/></>}</TabsContent>
 <TabsContent value="audit"><Panel title="Immutable signal ledger" tag="ORIGINAL SIGNAL / CURRENT RESULT"><div className="section-body"><div className="toolbar"><Button onClick={async()=>{try{setAudit(await api('/api/audit'))}catch(e){setError((e as Error).message)}}}><ShieldCheck size={14}/>Verify integrity</Button><Button variant="outline" onClick={()=>download('time-wheel-signals.json',signals)}><Download size={14}/>Export visible records</Button><Button variant="outline" onClick={refresh}>Refresh</Button></div>{audit&&<div className="notice">{audit.valid?'Integrity verified':'INTEGRITY FAILURE'} · {audit.count} original signals checked.<br/>{audit.scope}</div>}<p className="panel-note">Original payloads cannot be updated or deleted through the application or ordinary database writes. Later results are appended separately. Historical reconstructions are labeled and are not presented as forecasts made live.</p><div className="scroll-table"><table className="data-table"><thead><tr><th>Original time / source</th><th>TF</th><th>Signal</th><th>Price</th><th>Evidence score</th><th>Target 1</th><th>Later results</th><th>Audit details</th></tr></thead><tbody>{signals.map(s=>{const p=s.payload;return <tr key={s.id}><td>{date(p.timestamp)}<br/><span className="pill">{p.source} · {p.status}</span></td><td>{p.timeframe}</td><td className={p.direction==='BUY'?'positive':p.direction==='SELL'?'negative':''}>{p.direction}</td><td>{fmt(p.price)}</td><td>{fmt(p.confidence,1)}</td><td>{fmt(p.targets?.[0]?.price)}</td><td>{s.results.length?s.results.map((r:any)=><div key={r.horizon_seconds}>{r.horizon_seconds/60}m: {fmt(r.directional_change)}</div>):'Not yet available'}</td><td><details><summary>Inspect</summary><pre>{JSON.stringify({original:p,created_at:s.created_at,hash:s.hash,results:s.results},null,2)}</pre></details></td></tr>})}</tbody></table>{!signals.length&&<div className="empty">No signals logged yet. Connect market data or select a historical dataset.</div>}</div></div></Panel></TabsContent><TabsContent value="execution-history"><ExecutionHistory symbol={snapshot?.symbol||activeSymbol||"No symbol selected"}/></TabsContent></Tabs><footer>Signals are probabilistic and are not guaranteed.<span>Independent mathematics · No proprietary algorithm claim</span></footer></main>
}
class RenderBoundary extends Component<{children:React.ReactNode},{error:Error|null}>{
 state:{error:Error|null}={error:null};
 static getDerivedStateFromError(error:Error){return {error};}
 render(){return this.state.error?<main className="terminal"><div className="notice error" role="alert"><h2>Market unavailable</h2><p>The dashboard could not render this snapshot safely.</p><small>{this.state.error.message}</small></div></main>:this.props.children;}
}
export default function App(){return <RenderBoundary><Home/></RenderBoundary>}
