'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Choice,Field,Check,fmt,date,download} from './Controls';
import {api,type Config} from '@/lib/api';
export function Metrics({value}:{value:any}){if(!value)return null;return <div className="metrics">{[['Trades',value.trades],['Win rate',value.win_rate==null?null:value.win_rate*100],['Profit factor',value.profit_factor],['Expectancy',value.expectancy],['Net P&L',value.net_pnl],['Max drawdown',value.max_drawdown],['Sharpe',value.sharpe],['Sortino',value.sortino]].map(([label,v])=><div className="metric" key={String(label)}><small>{label}</small><b>{fmt(v,label==='Trades'?0:2)}{label==='Win rate'&&v!=null?'%':''}</b></div>)}</div>}
function Curve({equity}:{equity:any[]}){if(!equity?.length)return null;const vals=equity.map(x=>x.value),lo=Math.min(...vals),hi=Math.max(...vals);const step=Math.max(1,Math.floor(vals.length/600));const points=vals.map((v,i)=>i%step===0||i===vals.length-1?`${i/Math.max(1,vals.length-1)*1000},${130-(v-lo)/Math.max(.001,hi-lo)*110}`:null).filter(Boolean).join(' ');return <div className="equity"><small>MARKED EQUITY · {fmt(lo)} — {fmt(hi)}</small><svg viewBox="0 0 1000 150" role="img" aria-label="Historical marked equity curve"><polyline points={points} fill="none" stroke="#d8b675" strokeWidth="2"/></svg></div>}
export default function Lab({config,datasets}:{config:Config,datasets:any[]}){
 const[did,setDid]=useState(''),[models,setModels]=useState(['A','HM24','HM12']),[train,setTrain]=useState(1000),[test,setTest]=useState(500),[job,setJob]=useState(''),[status,setStatus]=useState(''),[result,setResult]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[level,setLevel]=useState<any>(null),[reference,setReference]=useState(4270),[base,setBase]=useState(4454),[split,setSplit]=useState(.7);
 useEffect(()=>{if(!did&&datasets.length)setDid(datasets[0].id)},[datasets,did]);
 const refresh=()=>Promise.all([api('/api/backtests'),api('/api/experiments')]).then(([a,b])=>setHistory([...a,...b].sort((x,y)=>y.created_at.localeCompare(x.created_at))));useEffect(()=>{void refresh()},[]);
 useEffect(()=>{if(!job)return;let stopped=false;const timer=setInterval(async()=>{try{const r=await api('/api/jobs/'+job);if(stopped)return;if(r.status!=='running'){setJob('');if(r.status==='failed')setStatus(r.error);else{setResult(r.result);setStatus('Completed. Results use recorded data and the stored configuration.');void refresh()}}}catch(e){setStatus((e as Error).message);setJob('')}},1500);return()=>{stopped=true;clearInterval(timer)}},[job]);
 const run=async(kind:string)=>{try{setStatus('Running historical research…');setResult(null);const d=datasets.find(x=>x.id===did);const strategy={...config,symbol:d?.symbol||config.symbol};const body=kind==='backtests'?{dataset_id:did,strategy,split_fraction:split}:{dataset_id:did,strategies:models.map(m=>({...strategy,name:config.name+' · '+m,time_model:m})),train_size:train,test_size:test};const r=await api('/api/'+kind,{method:'POST',body:JSON.stringify(body)});setJob(r.job_id)}catch(e){setStatus((e as Error).message)}};
 const displayed=result?.test||result?.folds?.[result.folds.length-1]?.test;
 return <article className="panel"><div className="panel-title"><h2>Research Lab</h2><span>NO EDGE ASSUMED</span></div><div className="section-body"><div className="field-row"><Choice label="Historical dataset" value={did} options={datasets.map(d=>[d.id,`${d.symbol} · ${d.timeframe} · ${d.bars.toLocaleString()} bars`])} onChange={setDid}/><Field label="Training fraction · frozen-model test" value={split} onChange={setSplit}/><Field label="Walk-forward training bars" value={train} onChange={setTrain}/><Field label="Walk-forward test bars" value={test} onChange={setTest}/></div><h3 className="subheading">Compare time numerology models under the current settings</h3><div className="toolbar">{['A','B','C','D','E','F','G','H','HM24','HM12'].map(m=><Check key={m} label={m} checked={models.includes(m)} onChange={v=>setModels(v?[...models,m]:models.filter(x=>x!==m))}/>)}</div><p className="panel-note">Price mapping, cycle, gates and costs come from the saved model settings. A and B are equivalent. Walk-forward selection uses training data only; each test segment uses a frozen winner. Change settings and rerun to compare price formulas and cycles in the history below.</p><div className="toolbar"><Button disabled={!did||!!job} onClick={()=>run('backtests')}>Run train / test backtest</Button><Button variant="outline" disabled={!did||!models.length||!!job} onClick={()=>run('experiments')}>Run walk-forward comparison</Button><span role="status">{status}</span></div>
 {displayed&&<><h3 className="subheading">{result.folds?'Latest walk-forward test fold':'Out-of-sample results'}</h3><Metrics value={displayed.metrics}/><Curve equity={displayed.equity}/><div className="toolbar"><Button variant="outline" onClick={()=>download('time-wheel-research-result.json',result)}>Export complete run and forecasts</Button></div>{result.assistant&&<div className="notice">{result.assistant}</div>}{result.folds&&<div className="scroll-table"><table className="data-table"><thead><tr><th>Fold / model</th><th>Train expectancy</th><th>Test expectancy</th><th>Test trades</th><th>Assessment</th></tr></thead><tbody>{result.folds.map((f:any,i:number)=><tr key={i}><td>{i+1} · {f.selected.time_model}</td><td>{fmt(f.train_metrics.expectancy)}</td><td>{fmt(f.test.metrics.expectancy)}</td><td>{f.test.metrics.trades}</td><td className="negative">{f.warning||'No degradation flag'}</td></tr>)}</tbody></table></div>}
 <details className="detail"><summary>All metrics, 3 / 6 / 9 study and annual stability</summary><pre>{JSON.stringify({metrics:displayed.metrics,study:displayed.research_369,yearly:displayed.yearly,assumptions:displayed.assumptions},null,2)}</pre></details><details className="detail"><summary>Historical forecasts and future outcomes · first 200 shown</summary><table className="data-table"><thead><tr><th>Original timestamp</th><th>Direction</th><th>Price</th><th>Score</th><th>5m result</th><th>Original hash</th></tr></thead><tbody>{displayed.forecasts?.slice(0,200).map((f:any)=><tr key={f.original.timestamp}><td>{date(f.original.timestamp)}</td><td>{f.original.direction}</td><td>{fmt(f.original.price)}</td><td>{fmt(f.original.confidence,1)}</td><td>{fmt(f.results?.[0]?.directional_change)}</td><td>{f.original_hash.slice(0,12)}</td></tr>)}</tbody></table></details></>}
 <h3 className="subheading">Saved experiment comparison</h3><div className="scroll-table"><table className="data-table"><thead><tr><th>Run</th><th>Dataset</th><th>Mapping / cycle</th><th>OOS expectancy</th><th>OOS P&L</th><th>Inspect</th></tr></thead><tbody>{history.map(r=>{const t=r.test||r.folds?.[r.folds.length-1]?.test;return <tr key={r.id}><td>{r.created_at.slice(0,19).replace('T',' ')}<br/>{r.folds?'Walk-forward · last fold':'Frozen model'}</td><td>{r.dataset?.symbol} {r.dataset?.timeframe}</td><td>{t?.strategy?.price_mapping}<br/>{t?.strategy?.cycle_seconds}s · {t?.strategy?.time_model}</td><td>{fmt(t?.metrics?.expectancy)}</td><td>{fmt(t?.metrics?.net_pnl)}</td><td><Button variant="outline" onClick={()=>setResult(r)}>Inspect</Button></td></tr>})}</tbody></table>{!history.length&&<div className="empty">No completed research runs yet.</div>}</div>
 <h3 className="subheading">Objective price-level investigation</h3><div className="field-row"><Field label="Current reference price" value={base} onChange={setBase}/><Field label="Level to investigate" value={reference} onChange={setReference}/><Button variant="outline" onClick={async()=>{try{setLevel(await api('/api/research/levels',{method:'POST',body:JSON.stringify({prices:[base],reference,tolerance:1})}))}catch(e){setStatus((e as Error).message)}}}>Search declared model grid</Button></div>{level&&<><div className="notice">{level.conclusion} Tested {level.tested_combinations} combinations; {level.matches.length} matches. {level.warning}</div><details className="detail"><summary>Matching formulas, anchors and angular distances</summary><pre>{JSON.stringify(level,null,2)}</pre></details></>}
 </div></article>
}
