'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Choice,Check,Field} from './Controls';
import {api,type Config} from '@/lib/api';
const HARMONICS=[0,30,45,60,90,120,135,180,225,240,270,300,315,360];
const GATES=['price_time','price_angle','time_angle','complement','sum_369','all_369','repeated_digits','cycle_intersection','angular'];
export default function Settings({config,onSaved,visual,onVisual}:{config:Config,onSaved:(c:Config)=>void,visual:Config,onVisual:(c:Config)=>void}){
 const[c,setC]=useState(config),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setC(config),[config]);const set=(k:string,v:any)=>setC({...c,[k]:v});
 const save=async()=>{setBusy(true);try{const r=await api('/api/config',{method:'PUT',body:JSON.stringify(c)});onSaved(r.config);setMessage('Saved as strategy version '+r.version.slice(0,12))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 const num=(key:string,label:string)=><Field key={key} label={label} value={c[key]} onChange={v=>set(key,v)}/>;
 return <article className="panel"><div className="panel-title"><h2>Model settings</h2><span>CHANGES CREATE A STRATEGY VERSION</span></div><div className="section-body"><div className="settings-grid"><Field label="Strategy name" type="text" value={c.name} onChange={v=>set('name',v)}/><Field label="Market symbol" type="text" value={c.symbol} onChange={v=>set('symbol',v)}/><Field label="Analysis timezone (IANA) · not broker time" type="text" value={c.timezone} onChange={v=>set('timezone',v)}/><Choice label="Time numerology" value={c.time_model} options={['A','B','C','D','E','F','G','H','HM24','HM12']} onChange={v=>set('time_model',v)}/><Choice label="Time mapping" value={c.time_mapping} options={['continuous',['minute_step','Minute hand · video inference']]} onChange={v=>set('time_mapping',v)}/><Choice label="Cycle" value={String(c.cycle_seconds)} options={[["86400","24 hours"],["43200","12 hours"],["21600","6 hours"],["10800","3 hours"],["3600","1 hour"],["1800","30 minutes"],["900","15 minutes"],["300","5 minutes"],["60","1 minute"]]} onChange={v=>set('cycle_seconds',Number(v))}/><Choice label="Price mapping" value={c.price_mapping} options={['linear','mod36','sqrt','increment','anchor']} onChange={v=>set('price_mapping',v)}/>{num('anchor_price','Anchor price / Wheel Value')}{num('increment','Price increment')}{num('price_range','Price per revolution · linear')}{num('start_angle','Starting angle')}{num('tolerance','Angular tolerance °')}{num('price_decimals','Price root decimal precision')}{num('angle_decimals','Angle root decimal precision')}{num('threshold','Combined score threshold')}<Field label="Anchor time · ISO with timezone, or blank" type="text" value={c.anchor_time||''} onChange={v=>set('anchor_time',v||null)}/></div><div className="toolbar"><Check label="Clockwise" checked={c.clockwise} onChange={v=>set('clockwise',v)}/><Check label="Require an enabled gate" checked={c.require_gate} onChange={v=>set('require_gate',v)}/><Check label="3 / 6 / 9 outcome study" checked={c.enable_369} onChange={v=>set('enable_369',v)}/><Check label="Gann-inspired projections" checked={c.enable_gann} onChange={v=>set('enable_gann',v)}/></div>{c.time_model==='H'&&<Field label="Custom arithmetic: h, m, s, p, elapsed, date · + - * / %" type="text" value={c.custom_formula} onChange={v=>set('custom_formula',v)}/>}
 <h3 className="subheading">Enabled harmonic relationships</h3><div className="toolbar">{HARMONICS.map(h=><Check key={h} label={h+'°'} checked={c.harmonics.includes(h)} onChange={v=>set('harmonics',v?[...c.harmonics,h]:c.harmonics.filter((x:number)=>x!==h))}/>)}</div><h3 className="subheading">Digital Gates · experimental rules</h3><div className="settings-grid">{GATES.map(g=><Check key={g} label={g.replaceAll('_',' ')} checked={c.gates.includes(g)} onChange={v=>set('gates',v?[...c.gates,g]:c.gates.filter((x:string)=>x!==g))}/>)}</div>
 <h3 className="subheading">Signal evidence weights</h3><div className="settings-grid">{Object.entries(c.weights).map(([key,value])=><Field key={key} label={key.replaceAll('_',' ')} value={value} onChange={v=>set('weights',{...c.weights,[key]:v})}/>)}</div>
 <h3 className="subheading">Technical confirmation and swing detection</h3><div className="toolbar">{['EMA','SMA','RSI','ADX','ATR','MACD','BB'].map(g=><Check key={g} label={g} checked={c.indicators.includes(g)} onChange={v=>set('indicators',v?[...c.indicators,g]:c.indicators.filter((x:string)=>x!==g))}/>)}</div><div className="settings-grid">{num('ema_fast','Fast EMA')}{num('ema_slow','Slow EMA / MACD')}{num('sma_period','SMA period')}{num('indicator_period','RSI / ADX / ATR period')}{num('bb_period','Bollinger period')}{num('bb_std','Bollinger standard deviations')}{num('swing_strength','Pivot confirmation bars')}</div>
 <h3 className="subheading">Manual Fibonacci anchors · leave both blank for automatic swings</h3><div className="settings-grid"><Field label="Low" value={c.fib_low} onChange={v=>set('fib_low',v===''?null:v)}/><Field label="High" value={c.fib_high} onChange={v=>set('fib_high',v===''?null:v)}/><Choice label="Swing direction" value={c.fib_direction} options={['up','down']} onChange={v=>set('fib_direction',v)}/><Field label="Known at · ISO timestamp with timezone" type="text" value={c.fib_anchor_time||''} onChange={v=>set('fib_anchor_time',v||null)}/></div>
 <h3 className="subheading">Backtest execution assumptions · quote-price units</h3><div className="settings-grid">{num('spread','Round-trip spread')}{num('slippage','Slippage per side')}{num('fee','Fee per completed trade')}{num('max_hold_bars','Maximum holding bars')}{num('initial_equity','Initial equity · one-unit positions')}</div><div className="toolbar"><Button onClick={save} disabled={busy}>{busy?'Saving…':'Save strategy version'}</Button><span role="status">{message}</span></div>
 <h3 className="subheading">Wheel and chart display · local preferences</h3><div className="toolbar">{['numbers','angles','roots','prices','fibonacci','gates','targets','support'].map(k=><Check key={k} label={k} checked={visual[k]!==false} onChange={v=>onVisual({...visual,[k]:v})}/>)}</div><div className="settings-grid"><Field label="Wheel maximum width" value={visual.size||620} onChange={v=>onVisual({...visual,size:v})}/><Choice label="Number of rings" value={String(visual.rings||5)} options={['1','2','3','4','5']} onChange={v=>onVisual({...visual,rings:Number(v)})}/></div><p className="panel-note">A and B are mathematically equivalent digital-root models. HM24/HM12 omit seconds, as strongly inferred from the video. Evidence scores have not been calibrated as probabilities. All displayed prices use the selected mathematical mapping.</p></div></article>
}

