"""Walk-forward execution-risk replay using saved genuine MT5 candles.

Signals and exits are generated by the existing backtester. Only chronological
entry acceptance is changed; strategy formulas and signal generation are not.
"""
from __future__ import annotations
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
import sqlite3
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from backend.app.backtest import run_backtest
from backend.app.config import Strategy, TIMEFRAMES

DB = ROOT / "runtime" / "timewheel.sqlite3"
FORENSIC_START = int(datetime(2026, 9, 13, tzinfo=timezone.utc).timestamp())
WINDOWS = {
    "discovery": (int(datetime(2026, 8, 11, tzinfo=timezone.utc).timestamp()), int(datetime(2026, 8, 31, tzinfo=timezone.utc).timestamp())),
    "validation": (int(datetime(2026, 8, 31, tzinfo=timezone.utc).timestamp()), int(datetime(2026, 9, 6, tzinfo=timezone.utc).timestamp())),
    "holdout": (int(datetime(2026, 9, 6, tzinfo=timezone.utc).timestamp()), int(datetime(2026, 9, 11, tzinfo=timezone.utc).timestamp())),
}


def load_xau_bars():
    con = sqlite3.connect(DB)
    row = con.execute("select id,payload from datasets where payload like '%\"symbol\":\"XAUUSD\"%' and payload like '%\"timeframe\":\"M1\"%' limit 1").fetchone()
    if not row:
        raise RuntimeError("No saved genuine XAUUSD M1 dataset")
    rows = con.execute("select payload from candles where dataset_id=? order by time", (row[0],)).fetchall()
    return [json.loads(x[0]) for x in rows]


def stats(trades):
    vals = [t["pnl"] for t in trades]
    wins = [x for x in vals if x > 0]; losses = [x for x in vals if x < 0]
    equity = peak = dd = 0.0
    for t in sorted(trades, key=lambda x: (x["exit_time"], x["entry_time"])):
        equity += t["pnl"]; peak = max(peak, equity); dd = max(dd, peak-equity)
    return {"trades":len(vals),"wins":len(wins),"losses":len(losses),"win_rate":len(wins)/len(vals) if vals else None,
            "gross_profit":sum(wins),"gross_loss":sum(losses),"net_pnl":sum(vals),
            "profit_factor":sum(wins)/abs(sum(losses)) if losses else None,"expectancy":sum(vals)/len(vals) if vals else None,
            "average_win":sum(wins)/len(wins) if wins else None,"average_loss":sum(losses)/len(losses) if losses else None,
            "max_drawdown":dd,"max_single_loss":min(vals) if vals else None,
            "max_simultaneous_same_direction_exposure":max((t.get("same_dir_exposure",0) for t in trades),default=0)}


def filter_trades(candidates, cooldown=0, cap=None):
    accepted=[]; blocked=0; last={}; active=[]
    for t in sorted(candidates, key=lambda x:(x["entry_time"], x["timeframe"])):
        entry=t["entry_time"]; key=(t["symbol"],t["direction"])
        active=[a for a in active if a["exit_time"] > entry]
        same=[a for a in active if (a["symbol"],a["direction"])==key]
        prev=last.get(key)
        if prev is not None and cooldown and entry-prev < cooldown:
            blocked += 1; continue
        if cap is not None and len(same)>=cap:
            blocked += 1; continue
        t=dict(t); t["same_dir_exposure"]=len(same)+1
        accepted.append(t); active.append(t); last[key]=entry
    return accepted, blocked


def partition(items, window):
    lo,hi=window; return [t for t in items if lo <= t["entry_time"] < hi]


def metric_row(name, trades, blocked):
    s=stats(trades); s.update({"variant":name,"blocked_entries":blocked}); return s


def main():
    bars=load_xau_bars()
    base=Strategy(symbol="XAUUSD",anchor_price=4400,spread=0.3,slippage=0.05,fee=0)
    all_candidates=[]; raw_by_tf={}
    for tf in ("M1","M5","M15","M30","H1"):
        # Resample the genuine M1 dataset exactly as the feed does, preserving closed bars.
        step=TIMEFRAMES[tf]; grouped={}
        for b in bars:
            bucket=(b["time"]//step)*step
            g=grouped.setdefault(bucket, {"time":bucket,"open":b["open"],"high":b["high"],"low":b["low"],"close":b["close"],"tick_volume":0})
            g["high"]=max(g["high"],b["high"]); g["low"]=min(g["low"],b["low"]); g["close"]=b["close"]; g["tick_volume"]+=b.get("tick_volume",0)
        tf_bars=[grouped[k] for k in sorted(grouped)]
        result=run_backtest(tf_bars,base,tf,keep_signals=False)
        trades=[]
        for t in result["trades"]:
            x=dict(t); x["symbol"]="XAUUSD"; x["timeframe"]=tf; trades.append(x)
        raw_by_tf[tf]=trades; all_candidates.extend(trades)
    variants=[("baseline",0,None),("cooldown_60s",60,None),("cooldown_120s",120,None),("cooldown_180s",180,None),("cooldown_300s",300,None),("cap_1",0,1),("cap_2",0,2),("cooldown_60s_cap_1",60,1),("cooldown_120s_cap_1",120,1),("cooldown_300s_cap_1",300,1)]
    output={"source_dataset":"runtime/timewheel.sqlite3 genuine MT5 XAUUSD M1, resampled causally","forensic_excluded_before":FORENSIC_START,"windows":WINDOWS,"symbols":{"XAUUSD":{}},"timeframes":list(raw_by_tf),"variants":{}}
    for window, bounds in WINDOWS.items():
        output["symbols"]["XAUUSD"][window]={}
        pool=partition(all_candidates,bounds)
        for name,cd,cap in variants:
            accepted,blocked=filter_trades(pool,cd,cap)
            s=metric_row(name,accepted,blocked)
            s["by_timeframe"]={tf:stats([t for t in accepted if t["timeframe"]==tf]) for tf in raw_by_tf}
            s["buy"] = stats([t for t in accepted if t["direction"]=="BUY"])
            s["sell"] = stats([t for t in accepted if t["direction"]=="SELL"])
            s["holding_buckets"]={name2:stats([t for t in accepted if lo<=t["exit_time"]-t["entry_time"]<hi]) for name2,lo,hi in [("<1m",0,60),("1-5m",60,300),("5-15m",300,900),("15-60m",900,3600),(">60m",3600,10**12)]}
            output["symbols"]["XAUUSD"][window][name]=s
    out=ROOT/"runtime"/"cooldown_walk_forward.json"; out.write_text(json.dumps(output,indent=2),encoding="utf-8")
    print(json.dumps({w:{name:(m["trades"],m["net_pnl"]) for name,m in values.items()} for w,values in output["symbols"]["XAUUSD"].items()},indent=2))


if __name__=='__main__': main()
