import json
from pathlib import Path
d=json.loads(Path('runtime/timeframe_attribution.json').read_text())
def f(v): return '—' if v is None else f'{v:.2f}'
lines=['# Demo Timeframe Attribution Report','','Source: `ReportHistory-52960017.html` plus persisted execution records. Auto trading remained disabled; no order was sent. Timeframe is never inferred for unmatched rows.','', '## Match coverage','',f"- MT5 trades: **{d['report_trades']}**",f"- Matched by persisted ticket and symbol: **{d['matched_trades']}**",f"- Unmatched: **{d['unmatched_trades']}**",f"- Match coverage: **{d['match_pct']:.2f}%**",'', 'Coverage is too low for reliable whole-week timeframe conclusions. The matched subset is descriptive only.','', '## Matched performance by timeframe','', '| Timeframe | Trades | Wins | Losses | Win rate | Gross profit | Gross loss | Net P/L | PF | Expectancy | Avg win | Avg loss | Payoff | Largest win | Largest loss | Max DD | Win streak | Loss streak | Avg R:R |', '|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
for tf,m in sorted(d['by_timeframe'].items()): lines.append(f"| {tf} | {m['trades']} | {m['wins']} | {m['losses']} | {m['win_rate']*100:.1f}% | {m['gross_profit']:.2f} | {m['gross_loss']:.2f} | {m['net_pl']:.2f} | {f(m['profit_factor'])} | {f(m['expectancy'])} | {f(m['average_win'])} | {f(m['average_loss'])} | {f(m['payoff_ratio'])} | {m['largest_win']:.2f} | {m['largest_loss']:.2f} | {m['max_drawdown']:.2f} | {m['max_consecutive_wins']} | {m['max_consecutive_losses']} | {f(m['avg_rr'])} |")
lines += ['', '## Symbol + timeframe', '', '| Symbol/timeframe | Trades | Win rate | Net P/L | PF | Expectancy | Avg duration (min) | Median duration (min) | Avg SL | Avg TP | Avg R:R |', '|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
for key,m in sorted(d['by_symbol_timeframe'].items()): lines.append(f"| {key} | {m['trades']} | {m['win_rate']*100:.1f}% | {m['net_pl']:.2f} | {f(m['profit_factor'])} | {f(m['expectancy'])} | {f(m['avg_duration_min'])} | {f(m['median_duration_min'])} | {f(m['avg_sl'])} | {f(m['avg_tp'])} | {f(m['avg_rr'])} |")
lines += ['', '## BUY / SELL by timeframe', '', '| Timeframe | Side | Trades | Win rate | PF | Expectancy | Net P/L | Avg win | Avg loss |', '|---|---|---:|---:|---:|---:|---:|---:|---:|']
for tf, sides in sorted(d['buy_sell'].items()):
 for side,m in sides.items():
  wr='—' if m['win_rate'] is None else f"{m['win_rate']*100:.1f}%"
  lines.append(f"| {tf} | {side.upper()} | {m['trades']} | {wr} | {f(m['profit_factor'])} | {f(m['expectancy'])} | {m['net_pl']:.2f} | {f(m['average_win'])} | {f(m['average_loss'])} |")
lines += ['', '## Cluster classification', '', '| Category | Clusters | Trades represented |', '|---|---:|---:|']
for cat in ('LEGITIMATE_MULTI_TIMEFRAME','PROVEN_DUPLICATE_SAME_TIMEFRAME','UNRESOLVED'):
 cs=[c for c in d['clusters'] if c['classification']==cat]; lines.append(f"| {cat} | {len(cs)} | {sum(c['count'] for c in cs)} |")
lines += ['', '### Proven matched cluster', '', '| Open time | Symbol | Direction | Tickets | Timeframes | Signal IDs | Combined P/L | Classification |', '|---|---|---|---|---|---|---:|---|']
for c in d['clusters']:
 if c['classification']!='UNRESOLVED': lines.append(f"| {c['open_time']} | {c['symbol']} | {c['direction'].upper()} | {', '.join(c['tickets'])} | {', '.join(str(x) for x in c['timeframes'])} | {', '.join(str(x) for x in c['signal_ids'])} | {c['net_pl']:.2f} | {c['classification']} |")
lines += ['', 'No same-timeframe same-signal duplicate was proven. The 33 remaining clusters are unresolved because their tickets have no persisted timeframe/signal linkage.','', '## True duplicate rate', '', f"- Matched trades: {d['matched_trades']}", '- Proven duplicate trades: 0', '- Legitimate multi-timeframe matched trades: 2', '- Unresolved clusters: 33 (86 clustered trades)', '- Proven duplicate rate among matched trades: 0.00%', '', 'The unresolved cluster count must not be treated as duplicate execution.','', '## Large losses', '', 'The major XAUUSD losses from the report are UNMATCHED in the local execution database. Their originating timeframe cannot be determined without guessing. No timeframe is assigned to them.','', '| Report loss | Symbol | Direction | Ticket | Timeframe |', '|---:|---|---|---:|---|']
for t in sorted(d['unmatched'],key=lambda x:x['net_pl'])[:10]: lines.append(f"| {t['net_pl']:.2f} | {t['symbol']} | {t['direction'].upper()} | {t['position']} | UNMATCHED |")
lines += ['', '## Multi-timeframe exposure', '', '| Distinct matched timeframes in cluster | Events | Trades | Combined P/L | Avg event P/L | Worst event |', '|---:|---:|---:|---:|---:|---:|']
for k,m in sorted(d['exposure'].items(),key=lambda x:int(x[0])): lines.append(f"| {k} | {m['events']} | {m['trades']} | {m['combined_pl']:.2f} | {m['average_event_pl']:.2f} | {m['worst_event_loss']:.2f} |")
lines += ['', '## Holding-time and exit geometry', '', 'Holding-time buckets cannot be fully attributed by timeframe for unmatched rows. In the matched subset, H1 includes the 241-minute BTCUSD trade; XAUUSD H1 matched trades have average duration 11.65 minutes. Matched H1 average planned R:R is 0.21, M15 0.27, and M30 0.16. These samples are too small to establish systematic timeframe-level exit geometry.', '', '## Ranking and conclusion', '', 'The matched subset ranks H1 highest by net P/L (+24.73), followed by M15 (+0.70) and M30 (+0.36), but H1 has only six matched trades and no losses. No timeframe can be called worst from this coverage. The largest losses are overwhelmingly unmatched, so their timeframe attribution is unknown.', '', '**Highest-confidence next experiment:** repair/preserve durable ticket-to-execution linkage for every order, then repeat this attribution on a complete report. Do not add cooldowns, caps, timeframe disabling, SL/TP changes, or production defaults based on this incomplete linkage.']
Path('docs/DEMO_TIMEFRAME_ATTRIBUTION_REPORT.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('wrote report')
